root: true

env:
  browser: true
  node: true
  es2022: true

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:astro/recommended
  - plugin:jsx-a11y/recommended
  - prettier

parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: tsconfig.json
  extraFileExtensions: ['.astro']

overrides:
  - files: ['*.astro']
    parser: astro-eslint-parser
    parserOptions:
      parser: '@typescript-eslint/parser'

  - files: ['*.tsx']
    parserOptions:
      ecmaFeatures:
        jsx: true

rules:
  '@typescript-eslint/consistent-type-exports': error
  '@typescript-eslint/consistent-type-imports': error
  '@typescript-eslint/no-useless-empty-export': error

  no-console: warn
