root: true

env:
  node: true
  browser: true
  es2020: true

extends:
  - eslint:recommended
  - next/core-web-vitals
  - plugin:@typescript-eslint/recommended
  - plugin:import/recommended
  - plugin:import/typescript
  - prettier

parser: '@typescript-eslint/parser'
parserOptions:
  sourceType: module
  project: tsconfig.json

rules:
  '@typescript-eslint/consistent-type-imports': 2
  '@typescript-eslint/consistent-type-exports': 2
  '@typescript-eslint/no-useless-empty-export': 2

  import/order:
    - 2
    - groups: [builtin, external, internal, parent, sibling, index, object, type]

  import/no-unresolved: 2
  import/first: 2
  import/exports-last: 2
  import/no-duplicates: 2
  import/no-self-import: 2

  no-console: 1
